extern const GeoLayout ssl_area_1_geo[];
extern const GeoLayout ssl_area_1[];
extern const Collision ssl_area_1_collision[];
extern const MacroObject ssl_area_1_macro_objs[];
extern const GeoLayout ssl_area_2_geo[];
extern const GeoLayout ssl_area_2[];
extern const Collision ssl_area_2_collision[];
extern const MacroObject ssl_area_2_macro_objs[];
extern u8 ssl_dl_Sand_i8[];
extern u8 ssl_dl_Sign_ci4[];
extern u8 ssl_dl_Sign_pal_rgba16[];
extern u8 ssl_dl_Arrow_ci4[];
extern u8 ssl_dl_Arrow_pal_rgba16[];
extern u8 ssl_dl_Sand_ci4[];
extern u8 ssl_dl_Sand_pal_rgba16[];
extern u8 ssl_dl_Water_i4[];
extern u8 ssl_dl_Wave_i4[];
extern u8 ssl_dl_Cliff_i8[];
extern u8 ssl_dl_Brick_ci4[];
extern u8 ssl_dl_Brick_pal_rgba16[];
extern u8 ssl_dl_BrickInterior_ci4[];
extern u8 ssl_dl_BrickInterior_pal_rgba16[];
extern u8 ssl_dl_StoneWall_i8[];
extern Vtx ssl_dl_GeoMain_mesh_layer_1_vtx_0[41];
extern Gfx ssl_dl_GeoMain_mesh_layer_1_tri_0[];
extern Vtx ssl_dl_GeoMain_mesh_layer_1_vtx_1[24];
extern Gfx ssl_dl_GeoMain_mesh_layer_1_tri_1[];
extern Vtx ssl_dl_GeoMain_mesh_layer_1_vtx_2[415];
extern Gfx ssl_dl_GeoMain_mesh_layer_1_tri_2[];
extern Vtx ssl_dl_GeoMain_mesh_layer_1_vtx_3[86];
extern Gfx ssl_dl_GeoMain_mesh_layer_1_tri_3[];
extern Vtx ssl_dl_GeoMain_mesh_layer_1_vtx_4[69];
extern Gfx ssl_dl_GeoMain_mesh_layer_1_tri_4[];
extern Vtx ssl_dl_GeoMain_mesh_layer_1_vtx_5[9];
extern Gfx ssl_dl_GeoMain_mesh_layer_1_tri_5[];
extern Vtx ssl_dl_GeoMain_mesh_layer_1_vtx_6[234];
extern Gfx ssl_dl_GeoMain_mesh_layer_1_tri_6[];
extern Vtx ssl_dl_GeoMain_mesh_layer_1_vtx_7[118];
extern Gfx ssl_dl_GeoMain_mesh_layer_1_tri_7[];
extern Vtx ssl_dl_GeoMain_mesh_layer_1_vtx_8[4];
extern Gfx ssl_dl_GeoMain_mesh_layer_1_tri_8[];
extern Vtx ssl_dl_GeoMain_mesh_layer_5_vtx_0[4];
extern Gfx ssl_dl_GeoMain_mesh_layer_5_tri_0[];
extern Vtx ssl_dl_Skybox_mesh_layer_1_vtx_0[16];
extern Gfx ssl_dl_Skybox_mesh_layer_1_tri_0[];
extern Vtx ssl_dl_GeoMainArea2_mesh_layer_1_vtx_0[135];
extern Gfx ssl_dl_GeoMainArea2_mesh_layer_1_tri_0[];
extern Vtx ssl_dl_GeoMainArea2_mesh_layer_1_vtx_1[197];
extern Gfx ssl_dl_GeoMainArea2_mesh_layer_1_tri_1[];
extern Vtx ssl_dl_GeoMainArea2_mesh_layer_1_vtx_2[476];
extern Gfx ssl_dl_GeoMainArea2_mesh_layer_1_tri_2[];
extern Vtx ssl_dl_GeoMainArea2_mesh_layer_5_vtx_0[1532];
extern Gfx ssl_dl_GeoMainArea2_mesh_layer_5_tri_0[];
extern Gfx mat_ssl_dl_Sand[];
extern Gfx mat_revert_ssl_dl_Sand[];
extern Gfx mat_ssl_dl_SandStart[];
extern Gfx mat_revert_ssl_dl_SandStart[];
extern Gfx mat_ssl_dl_SandDeath[];
extern Gfx mat_revert_ssl_dl_SandDeath[];
extern Gfx mat_ssl_dl_Sign[];
extern Gfx mat_revert_ssl_dl_Sign[];
extern Gfx mat_ssl_dl_Arrow[];
extern Gfx mat_revert_ssl_dl_Arrow[];
extern Gfx mat_ssl_dl_DeathPlaneSand[];
extern Gfx mat_revert_ssl_dl_DeathPlaneSand[];
extern Gfx mat_ssl_dl_Water_layer5[];
extern Gfx mat_revert_ssl_dl_Water_layer5[];
extern Gfx mat_ssl_dl_Cliff[];
extern Gfx mat_revert_ssl_dl_Cliff[];
extern Gfx mat_ssl_dl_Brick[];
extern Gfx mat_revert_ssl_dl_Brick[];
extern Gfx mat_ssl_dl_InstaWarp[];
extern Gfx mat_revert_ssl_dl_InstaWarp[];
extern Gfx mat_ssl_dl_Skybox[];
extern Gfx mat_revert_ssl_dl_Skybox[];
extern Gfx mat_ssl_dl_BrickInteriorAlpha[];
extern Gfx mat_revert_ssl_dl_BrickInteriorAlpha[];
extern Gfx mat_ssl_dl_BrickInterior[];
extern Gfx mat_revert_ssl_dl_BrickInterior[];
extern Gfx mat_ssl_dl_StoneFloor[];
extern Gfx mat_revert_ssl_dl_StoneFloor[];
extern Gfx ssl_dl_GeoMain_mesh_layer_1[];
extern Gfx ssl_dl_GeoMain_mesh_layer_5[];
extern Gfx ssl_dl_Skybox_mesh_layer_1[];
extern Gfx ssl_dl_GeoMainArea2_mesh_layer_1[];
extern Gfx ssl_dl_GeoMainArea2_mesh_layer_5[];
