extern const GeoLayout ssl_area_1_geo[];
extern const GeoLayout ssl_area_1[];
extern const Collision ssl_area_1_collision[];
extern const MacroObject ssl_area_1_macro_objs[];
extern Lights1 ssl_dl_DeathPlane_lights;
extern u8 ssl_dl_Sand_i8[];
extern Vtx ssl_dl_Cube_mesh_layer_5_vtx_0[4];
extern Gfx ssl_dl_Cube_mesh_layer_5_tri_0[];
extern Vtx ssl_dl_Cube_mesh_layer_1_vtx_0[35];
extern Gfx ssl_dl_Cube_mesh_layer_1_tri_0[];
extern Vtx ssl_dl_Cube_mesh_layer_1_vtx_1[36];
extern Gfx ssl_dl_Cube_mesh_layer_1_tri_1[];
extern Vtx ssl_dl_Skybox_mesh_layer_1_vtx_0[28];
extern Gfx ssl_dl_Skybox_mesh_layer_1_tri_0[];
extern Gfx mat_ssl_dl_DeathPlane[];
extern Gfx mat_ssl_dl_Sand[];
extern Gfx mat_revert_ssl_dl_Sand[];
extern Gfx mat_ssl_dl_SandDeath[];
extern Gfx mat_revert_ssl_dl_SandDeath[];
extern Gfx mat_ssl_dl_Skybox[];
extern Gfx mat_revert_ssl_dl_Skybox[];
extern Gfx ssl_dl_Cube_mesh_layer_5[];
extern Gfx ssl_dl_Cube_mesh_layer_1[];
extern Gfx ssl_dl_Skybox_mesh_layer_1[];
