extern const GeoLayout bob_area_1_geo[];
extern const GeoLayout bob_area_1[];
extern const Collision bob_area_1_collision[];
extern const MacroObject bob_area_1_macro_objs[];
extern Lights1 bob_dl_DeathPlane_lights;
extern u8 bob_dl_Grass_i8[];
extern u8 bob_dl_Cliff_ci8[];
extern u8 bob_dl_Cliff_pal_rgba16[];
extern u8 bob_dl_Water_i4[];
extern u8 bob_dl_Wave_i4[];
extern u8 bob_dl_RockCliff_i8[];
extern Vtx bob_dl_Cube_mesh_layer_1_vtx_0[93];
extern Gfx bob_dl_Cube_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Cube_mesh_layer_1_vtx_1[140];
extern Gfx bob_dl_Cube_mesh_layer_1_tri_1[];
extern Vtx bob_dl_Cube_mesh_layer_1_vtx_2[4];
extern Gfx bob_dl_Cube_mesh_layer_1_tri_2[];
extern Vtx bob_dl_Cube_mesh_layer_1_vtx_3[249];
extern Gfx bob_dl_Cube_mesh_layer_1_tri_3[];
extern Vtx bob_dl_Cube_mesh_layer_5_vtx_0[4];
extern Gfx bob_dl_Cube_mesh_layer_5_tri_0[];
extern Vtx bob_dl_Cube_mesh_layer_5_vtx_1[12];
extern Gfx bob_dl_Cube_mesh_layer_5_tri_1[];
extern Vtx bob_dl_Cube_mesh_layer_5_vtx_2[52];
extern Gfx bob_dl_Cube_mesh_layer_5_tri_2[];
extern Vtx bob_dl_Plane_mesh_layer_1_vtx_0[480];
extern Gfx bob_dl_Plane_mesh_layer_1_tri_0[];
extern Vtx bob_dl_SkyMain_mesh_layer_1_vtx_0[43];
extern Gfx bob_dl_SkyMain_mesh_layer_1_tri_0[];
extern Gfx mat_bob_dl_Grass[];
extern Gfx mat_revert_bob_dl_Grass[];
extern Gfx mat_bob_dl_DeathPlane[];
extern Gfx mat_bob_dl_Cliff[];
extern Gfx mat_revert_bob_dl_Cliff[];
extern Gfx mat_bob_dl_Water_layer1[];
extern Gfx mat_revert_bob_dl_Water_layer1[];
extern Gfx mat_bob_dl_RockCliff[];
extern Gfx mat_revert_bob_dl_RockCliff[];
extern Gfx mat_bob_dl_WaterAlpha_layer5[];
extern Gfx mat_revert_bob_dl_WaterAlpha_layer5[];
extern Gfx mat_bob_dl_GrassEdge[];
extern Gfx mat_revert_bob_dl_GrassEdge[];
extern Gfx mat_bob_dl_Sky[];
extern Gfx mat_revert_bob_dl_Sky[];
extern Gfx bob_dl_Cube_mesh_layer_1[];
extern Gfx bob_dl_Cube_mesh_layer_5[];
extern Gfx bob_dl_Plane_mesh_layer_1[];
extern Gfx bob_dl_SkyMain_mesh_layer_1[];
