extern const GeoLayout lll_area_1_geo[];
extern const GeoLayout lll_area_1[];
extern const Collision lll_area_1_collision[];
extern const MacroObject lll_area_1_macro_objs[];
extern const GeoLayout lll_area_2_geo[];
extern const GeoLayout lll_area_2[];
extern const Collision lll_area_2_collision[];
extern const MacroObject lll_area_2_macro_objs[];
extern u8 lll_dl_Platform_ci4[];
extern u8 lll_dl_Platform_pal_rgba16[];
extern u8 lll_dl_VolcanoRock_ci4[];
extern u8 lll_dl_VolcanoRock_pal_rgba16[];
extern u8 lll_dl_Grass_i8[];
extern u8 lll_dl_Lava1_i8[];
extern u8 lll_dl_Lava2_i8[];
extern u8 lll_dl_StoneWall_i8[];
extern u8 lll_dl_Rail_ci4[];
extern u8 lll_dl_Rail_pal_rgba16[];
extern Vtx lll_dl_GeoArea1_mesh_layer_1_vtx_0[24];
extern Gfx lll_dl_GeoArea1_mesh_layer_1_tri_0[];
extern Vtx lll_dl_GeoArea1_mesh_layer_1_vtx_1[55];
extern Gfx lll_dl_GeoArea1_mesh_layer_1_tri_1[];
extern Vtx lll_dl_GeoArea1_mesh_layer_1_vtx_2[117];
extern Gfx lll_dl_GeoArea1_mesh_layer_1_tri_2[];
extern Vtx lll_dl_GeoArea1_mesh_layer_1_vtx_3[89];
extern Gfx lll_dl_GeoArea1_mesh_layer_1_tri_3[];
extern Vtx lll_dl_GeoArea1_mesh_layer_1_vtx_4[24];
extern Gfx lll_dl_GeoArea1_mesh_layer_1_tri_4[];
extern Vtx lll_dl_GeoArea1_mesh_layer_1_vtx_5[44];
extern Gfx lll_dl_GeoArea1_mesh_layer_1_tri_5[];
extern Vtx lll_dl_GeoArea1_mesh_layer_5_vtx_0[28];
extern Gfx lll_dl_GeoArea1_mesh_layer_5_tri_0[];
extern Vtx lll_dl_Skybox_mesh_layer_1_vtx_0[38];
extern Gfx lll_dl_Skybox_mesh_layer_1_tri_0[];
extern Vtx lll_dl_GeoArea2_mesh_layer_1_vtx_0[18];
extern Gfx lll_dl_GeoArea2_mesh_layer_1_tri_0[];
extern Vtx lll_dl_GeoArea2_mesh_layer_1_vtx_1[512];
extern Gfx lll_dl_GeoArea2_mesh_layer_1_tri_1[];
extern Vtx lll_dl_GeoArea2_mesh_layer_1_vtx_2[4];
extern Gfx lll_dl_GeoArea2_mesh_layer_1_tri_2[];
extern Vtx lll_dl_GeoArea2_mesh_layer_4_vtx_0[920];
extern Gfx lll_dl_GeoArea2_mesh_layer_4_tri_0[];
extern Vtx lll_dl_GeoArea2_mesh_layer_4_vtx_1[4];
extern Gfx lll_dl_GeoArea2_mesh_layer_4_tri_1[];
extern Gfx mat_lll_dl_Wood[];
extern Gfx mat_revert_lll_dl_Wood[];
extern Gfx mat_lll_dl_VolcanoRock_Deathplane[];
extern Gfx mat_revert_lll_dl_VolcanoRock_Deathplane[];
extern Gfx mat_lll_dl_VolcanoRock[];
extern Gfx mat_revert_lll_dl_VolcanoRock[];
extern Gfx mat_lll_dl_Grass[];
extern Gfx mat_revert_lll_dl_Grass[];
extern Gfx mat_lll_dl_GrassAlpha[];
extern Gfx mat_revert_lll_dl_GrassAlpha[];
extern Gfx mat_lll_dl_Lava_layer1[];
extern Gfx mat_revert_lll_dl_Lava_layer1[];
extern Gfx mat_lll_dl_StoneWall[];
extern Gfx mat_revert_lll_dl_StoneWall[];
extern Gfx mat_lll_dl_Sky[];
extern Gfx mat_revert_lll_dl_Sky[];
extern Gfx mat_lll_dl_Rail[];
extern Gfx mat_revert_lll_dl_Rail[];
extern Gfx mat_lll_dl_TimeEnd[];
extern Gfx mat_revert_lll_dl_TimeEnd[];
extern Gfx mat_lll_dl_RailStart[];
extern Gfx mat_revert_lll_dl_RailStart[];
extern Gfx lll_dl_GeoArea1_mesh_layer_1[];
extern Gfx lll_dl_GeoArea1_mesh_layer_5[];
extern Gfx lll_dl_Skybox_mesh_layer_1[];
extern Gfx lll_dl_GeoArea2_mesh_layer_1[];
extern Gfx lll_dl_GeoArea2_mesh_layer_4[];
